//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyAuth.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiyAuth.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;##__Subject__##&lt;/title&gt;
        ///    &lt;style&gt;
        ///
        ///    @media only screen and (max-width: 620px) {
        ///      table[class=body] h1 {
        ///        font-size: 28px !important;
        ///        margin-bottom: 10px !important;
        ///      }
        ///      table[class=body] p,
        ///            table[class=body] ul,
        ///            table[class=body] ol,
        ///            table[class=body] td [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgotPasswordTemplate {
            get {
                return ResourceManager.GetString("ForgotPasswordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;##__Subject__##&lt;/title&gt;
        ///    &lt;style&gt;
        ///
        ///    @media only screen and (max-width: 620px) {
        ///      table[class=body] h1 {
        ///        font-size: 28px !important;
        ///        margin-bottom: 10px !important;
        ///      }
        ///      table[class=body] p,
        ///            table[class=body] ul,
        ///            table[class=body] ol,
        ///            table[class=body] td [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoFactorTemplate {
            get {
                return ResourceManager.GetString("TwoFactorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;title&gt;##__Subject__##&lt;/title&gt;
        ///	&lt;style&gt;
        ///
        ///	@media only screen and (max-width: 620px) {
        ///	  table[class=body] h1 {
        ///		font-size: 28px !important;
        ///		margin-bottom: 10px !important;
        ///	  }
        ///	  table[class=body] p,
        ///			table[class=body] ul,
        ///			table[class=body] ol,
        ///			table[class=body] td,
        ///			table[class=body] span,
        ///			table[class=body] a {
        ///		font [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VerificationTokenTemplate {
            get {
                return ResourceManager.GetString("VerificationTokenTemplate", resourceCulture);
            }
        }
    }
}
